import type { Metadata } from "next";
import IndexRoot from "./indexRoot";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function IndexLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
        <IndexRoot/>
      </body>
    </html>
  );
}
